# Generated by Django 4.1 on 2026-07-28 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('code', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('per_pound', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.client')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QR_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3)),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(max_length=20)),
                ('order_number', models.TextField(max_length=20)),
                ('start_qty', models.IntegerField()),
                ('current_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('QR_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testQR.qr_token')),
                ('parent_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testQR.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.process')),
            ],
        ),
        migrations.AddField(
            model_name='qr_token',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.station'),
        ),
        migrations.CreateModel(
            name='Process_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('order', models.IntegerField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.part_number')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.process')),
            ],
        ),
    ]
