# Generated by Django 4.1 on 2026-07-28 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.TextField(max_length=20)),
                ('order_number', models.TextField(max_length=20)),
                ('start_qty', models.IntegerField()),
                ('current_qty', models.IntegerField()),
                ('created_by', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('QR_token', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testQR.qr_token')),
                ('parent_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testQR.work_order')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
