# Generated by Django 4.1 on 2026-07-28 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0002_work_order_delete_workorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order',
            name='order_number',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testQR.part_number')),
            ],
        ),
        migrations.AddField(
            model_name='work_order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testQR.order'),
            preserve_default=False,
        ),
    ]
