# Generated by Django 4.1 on 2026-07-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0003_remove_work_order_order_number_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='process',
        ),
        migrations.AddField(
            model_name='part_number',
            name='thickness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='processes',
            field=models.ManyToManyField(related_name='stations', to='testQR.process'),
        ),
    ]
