# Generated by Django 4.1 on 2026-07-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0004_remove_station_process_part_number_thickness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='long_name',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
