# Generated by Django 4.1 on 2026-07-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0005_station_long_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='QR_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='testQR.qr_token'),
        ),
    ]
