# Generated by Django 4.1 on 2026-07-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0006_alter_work_order_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
