# Generated by Django 4.1 on 2026-07-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0007_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_step',
            name='name',
        ),
    ]
