# Generated by Django 4.1 on 2026-07-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0008_remove_process_step_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_order',
            name='part_number',
        ),
    ]
