# Generated by Django 4.1 on 2026-07-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0009_remove_work_order_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work_order',
            name='current_bins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work_order',
            name='start_bins',
            field=models.IntegerField(default=0),
        ),
    ]
