# Generated by Django 4.1 on 2026-07-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0010_order_bins_work_order_current_bins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='created_by',
            field=models.TextField(),
        ),
    ]
