# Generated by Django 4.1 on 2026-07-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0011_alter_work_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr_token',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_here', to='testQR.station'),
        ),
        migrations.AlterField(
            model_name='qr_token',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tokens', to='testQR.station'),
        ),
    ]
