# Generated by Django 4.1 on 2026-07-31 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0012_qr_token_current_location_alter_qr_token_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_token',
            old_name='current_location',
            new_name='location',
        ),
    ]
