# Generated by Django 4.1 on 2026-07-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testQR', '0013_rename_current_location_qr_token_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
