# Generated by Django 5.1.4 on 2025-04-14 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='related_words',
            field=models.ManyToManyField(to='cards.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Other_related_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=30)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
