# Generated by Django 5.1.4 on 2025-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_related_words_card_user_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='other_related_words',
            name='word',
            field=models.TextField(max_length=100),
        ),
    ]
