# Generated by Django 5.1.4 on 2025-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_word_alter_other_related_words_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reliability',
            field=models.IntegerField(default=1),
        ),
    ]
