# Generated by Django 4.1 on 2025-03-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reps_and_weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weightInKilos', models.BooleanField(default=False)),
                ('reps', models.DecimalField(decimal_places=0, max_digits=2)),
                ('order', models.DecimalField(decimal_places=0, max_digits=1)),
                ('is_warmup', models.BooleanField(default=False)),
                ('difficulty', models.DecimalField(decimal_places=0, max_digits=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercisapp.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=40, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts_in_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.DecimalField(decimal_places=0, max_digits=2)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercisapp.plan')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercisapp.workout')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise_in_program',
            name='program',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
