# Generated by Django 4.1 on 2025-03-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0002_plan_reps_and_weights_workout_workouts_in_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_in_program',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise_in_program',
            name='order',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise_in_program',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.workout'),
            preserve_default=False,
        ),
    ]
