# Generated by Django 4.1 on 2025-03-24 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0003_exercise_in_program_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reps_and_weights',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 24, 19, 19, 26, 711945, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reps_and_weights',
            name='set',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
            preserve_default=False,
        ),
    ]
