# Generated by Django 4.1 on 2025-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0004_reps_and_weights_created_at_reps_and_weights_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='reps_and_weights',
            name='weightPerSide',
            field=models.BooleanField(default=False),
        ),
    ]
