# Generated by Django 4.1 on 2025-03-24 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercisapp', '0006_exercise_description_reps_and_weights_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='workout',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercisapp.workout')),
            ],
        ),
        migrations.AddField(
            model_name='reps_and_weights',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.session'),
            preserve_default=False,
        ),
    ]
