# Generated by Django 4.1 on 2025-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0007_remove_reps_and_weights_workout_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reps_and_weights',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
