# Generated by Django 4.1 on 2025-03-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0008_alter_reps_and_weights_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='weightInKilos',
        ),
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='weightPerSide',
        ),
        migrations.AddField(
            model_name='session',
            name='weightInKilos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='weightPerSide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reps_and_weights',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='reps_and_weights',
            name='reps',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reps_and_weights',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
