# Generated by Django 4.1 on 2025-03-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0009_remove_reps_and_weights_weightinkilos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='weightInKilos',
        ),
        migrations.RemoveField(
            model_name='session',
            name='weightPerSide',
        ),
        migrations.AlterField(
            model_name='session',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Session_workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('units_kg', models.BooleanField(default=False)),
                ('weight_per_side', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.exercise')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.session')),
            ],
        ),
    ]
