# Generated by Django 4.1 on 2025-03-25 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0010_remove_session_weightinkilos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reps_and_weights',
            name='session',
        ),
        migrations.AlterField(
            model_name='reps_and_weights',
            name='reps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reps_and_weights',
            name='set',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
