# Generated by Django 4.1 on 2025-03-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0011_remove_reps_and_weights_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reps_and_weights',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.session_workout'),
            preserve_default=False,
        ),
    ]
