# Generated by Django 4.1 on 2025-03-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0012_reps_and_weights_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reps_and_weights',
            old_name='session',
            new_name='session_workout',
        ),
    ]
