# Generated by Django 4.1 on 2025-03-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0013_rename_session_reps_and_weights_session_workout'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='session_workout',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.exercise'),
            preserve_default=False,
        ),
    ]