# Generated by Django 4.1 on 2025-03-26 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercisapp', '0014_new_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts_in_plan',
            name='plan',
        ),
        migrations.AddField(
            model_name='workouts_in_plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session_workout',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisapp.exercise'),
        ),
        migrations.AlterField(
            model_name='workouts_in_plan',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
