# Generated by Django 4.1 on 2025-03-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0015_remove_workouts_in_plan_plan_workouts_in_plan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='workout_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercisapp.workout'),
        ),
    ]
