# Generated by Django 4.1 on 2025-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0016_alter_session_workout_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_workout',
            name='units_kg',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='session_workout',
            name='weight_per_side',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
