# Generated by Django 4.1 on 2025-04-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercisapp', '0018_alter_session_workout_units_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BinaryField(default=False)),
                ('friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requester', to=settings.AUTH_USER_MODEL)),
                ('friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
