# Generated by Django 4.1 on 2025-04-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisapp', '0019_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
