# Generated by Django 4.1 on 2024-08-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esl_ny', '0002_alter_borough_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esl_ny.borough')),
            ],
        ),
    ]
