# Generated by Django 4.1 on 2024-08-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl_ny', '0003_communitydistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
