# Generated by Django 4.1 on 2024-08-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esl_ny', '0004_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEPPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lep_population', models.IntegerField()),
                ('cvalep_population', models.IntegerField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esl_ny.borough')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esl_ny.language')),
            ],
        ),
    ]
