# Generated by Django 4.1 on 2024-08-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esl_ny', '0005_leppopulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leppopulation',
            name='borough',
        ),
        migrations.AddField(
            model_name='leppopulation',
            name='communitydistrict',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='esl_ny.communitydistrict'),
            preserve_default=False,
        ),
    ]
