# Generated by Django 4.1 on 2024-08-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esl_ny', '0006_remove_leppopulation_borough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydistrict',
            name='geojson',
            field=models.JSONField(default={'data': 'nothing'}),
            preserve_default=False,
        ),
    ]
